spring.application.name=ms-integracion-multicanal
server.port=8083

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gestion_centralizada_reclamos}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Qwepoizxcmnb123@}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.time-zone=America/Santiago
