spring.application.name=ms-usuarios-autenticacion
server.port=${SERVER_PORT:8081}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gestion_centralizada_reclamos}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Qwepoizxcmnb123@}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.security.password-pepper=${PASSWORD_PEPPER:GCR_2026_p3pp3r_R3cl4m0s_Omn1c4n4l_AWS_RDS_LOCAL_x9Kq7Lm2Vz}
app.security.jwt-secret=${JWT_SECRET:GCR_2026_jwt_s3cr3t_local_demo_Cambiar_en_AWS_7Lm9Qp2Rx}
app.security.jwt-expiration-minutes=${JWT_EXPIRATION_MINUTES:480}

logging.level.org.springframework.security=${SECURITY_LOG_LEVEL:INFO}
