export const PERFILES = {
  ATENCION_CLIENTE: 'ATENCION_CLIENTE',
  POSTVENTA: 'POSTVENTA',
  OPERACIONES: 'OPERACIONES',
  GERENCIA: 'GERENCIA',
  SOPORTE_TECNICO: 'SOPORTE_TECNICO',
  OTRO: 'OTRO',
};
